name: konstruado_de_eldonaĵo
# Triggera Maniero.
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    # Ĉar necesas krei eldonaĵon, necesas agordi skribpermeson.
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Elpaki Deponejon
        uses: actions/checkout@v4
      
      - name: Instali Rust-stabilan
        uses: dtolnay/rust-toolchain@stable

      - name: Agordi Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Agordi Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Instali Antaŭpartajn Dependaĵojn
        run: bun install

      - name: Kontroli Informojn pri Sekretoj
        run: |
          echo "=== Private Key Analysis ==="
          if [ -n "$TAURI_KEY" ]; then
            echo "✓ Private Key is set"
            echo "Key length: ${#TAURI_KEY} characters"
            echo "First 10 chars: '$(echo -n "$TAURI_KEY" | head -c 10)'"
            echo "Last 10 chars: '$(echo -n "$TAURI_KEY" | tail -c 10)'"
            echo "First line: '$(echo "$TAURI_KEY" | head -1)'"
            echo "Last line: '$(echo "$TAURI_KEY" | tail -1)'"
          else
            echo "✗ Private Key is empty"
          fi

          echo ""
          echo "=== Password Analysis ==="
          if [ -n "$TAURI_PWD" ]; then
            echo "✓ Password is set"
            echo "Password length: ${#TAURI_PWD} characters"
            echo "First 5 chars: '$(echo -n "$TAURI_PWD" | head -c 5)'"
            echo "Last 5 chars: '$(echo -n "$TAURI_PWD" | tail -c 5)'"
          else
            echo "✗ Password is empty"
          fi

        # Uzi Tauri-actions
      # - name: Konstrui la Aplikaĵon
      #   id: build
      #   uses: tauri-apps/tauri-action@v0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # Privata Ŝlosilo
      #     TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      #     # Pasfrazo por la Privata Ŝlosilo
      #     TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
      #   with:
      #     tagName: app-v__VERSION__
      #     releaseName: "App v__VERSION__"
      #     releaseBody: "Vidu la resursojn por elŝuti kaj instali ĉi tiun version."
      #     releaseDraft: true
      #     prerelease: false
      #     args: ${{ matrix.args }}

      # - name: Ruli sian propran skripton
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: bun .github\Skriptoj\ĝisdatigilo.mjs
